-- Seed data for the anonymous shared pool (user_id is null).
-- Run in the Supabase SQL editor after schema.sql. Re-runnable: clears the
-- anonymous pool first, never touches user-owned rows.

delete from public.books where user_id is null;

insert into public.books (title, author, status, rating, created_at, updated_at)
select v.title, v.author, v.status, v.rating,
       now() - (v.rn * interval '7 hours'),
       now() - (v.rn * interval '7 hours')
from (
  select t.*, row_number() over () as rn
  from (values
    ('The Great Gatsby', 'F. Scott Fitzgerald', 'finished', 4),
    ('To Kill a Mockingbird', 'Harper Lee', 'finished', 5),
    ('1984', 'George Orwell', 'finished', 5),
    ('Pride and Prejudice', 'Jane Austen', 'finished', 4),
    ('The Catcher in the Rye', 'J. D. Salinger', 'finished', 3),
    ('Brave New World', 'Aldous Huxley', 'finished', 4),
    ('The Hobbit', 'J. R. R. Tolkien', 'finished', 5),
    ('Fahrenheit 451', 'Ray Bradbury', 'finished', 4),
    ('Jane Eyre', 'Charlotte Brontë', 'finished', 4),
    ('Animal Farm', 'George Orwell', 'finished', 4),
    ('The Old Man and the Sea', 'Ernest Hemingway', 'finished', 3),
    ('Of Mice and Men', 'John Steinbeck', 'finished', 4),
    ('Slaughterhouse-Five', 'Kurt Vonnegut', 'finished', 5),
    ('Catch-22', 'Joseph Heller', 'finished', 4),
    ('The Bell Jar', 'Sylvia Plath', 'finished', 4),
    ('Frankenstein', 'Mary Shelley', 'finished', 4),
    ('Dracula', 'Bram Stoker', 'finished', 3),
    ('Wuthering Heights', 'Emily Brontë', 'finished', 3),
    ('Great Expectations', 'Charles Dickens', 'finished', 3),
    ('Crime and Punishment', 'Fyodor Dostoevsky', 'finished', 5),
    ('The Picture of Dorian Gray', 'Oscar Wilde', 'finished', 4),
    ('Lord of the Flies', 'William Golding', 'finished', 3),
    ('The Grapes of Wrath', 'John Steinbeck', 'finished', 4),
    ('One Hundred Years of Solitude', 'Gabriel García Márquez', 'finished', 5),
    ('Beloved', 'Toni Morrison', 'finished', 5),
    ('The Handmaid''s Tale', 'Margaret Atwood', 'finished', 4),
    ('The Road', 'Cormac McCarthy', 'finished', 4),
    ('Never Let Me Go', 'Kazuo Ishiguro', 'finished', 4),
    ('The Remains of the Day', 'Kazuo Ishiguro', 'finished', 5),
    ('Norwegian Wood', 'Haruki Murakami', 'finished', 3),
    ('Kafka on the Shore', 'Haruki Murakami', 'finished', 4),
    ('The Kite Runner', 'Khaled Hosseini', 'finished', 4),
    ('Life of Pi', 'Yann Martel', 'finished', 3),
    ('The Book Thief', 'Markus Zusak', 'finished', 4),
    ('Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 'finished', 4),
    ('Middlemarch', 'George Eliot', 'reading', null),
    ('Anna Karenina', 'Leo Tolstoy', 'reading', null),
    ('Ulysses', 'James Joyce', 'reading', null),
    ('Infinite Jest', 'David Foster Wallace', 'reading', null),
    ('The Brothers Karamazov', 'Fyodor Dostoevsky', 'reading', null),
    ('Moby-Dick', 'Herman Melville', 'reading', null),
    ('Don Quixote', 'Miguel de Cervantes', 'reading', null),
    ('A Little Life', 'Hanya Yanagihara', 'reading', null),
    ('The Goldfinch', 'Donna Tartt', 'reading', null),
    ('The Name of the Wind', 'Patrick Rothfuss', 'reading', null),
    ('Educated', 'Tara Westover', 'reading', null),
    ('Thinking, Fast and Slow', 'Daniel Kahneman', 'reading', null),
    ('The Wind-Up Bird Chronicle', 'Haruki Murakami', 'reading', null),
    ('Cloud Atlas', 'David Mitchell', 'reading', null),
    ('Wolf Hall', 'Hilary Mantel', 'reading', null),
    ('Dune', 'Frank Herbert', 'to_read', null),
    ('Foundation', 'Isaac Asimov', 'to_read', null),
    ('Neuromancer', 'William Gibson', 'to_read', null),
    ('Snow Crash', 'Neal Stephenson', 'to_read', null),
    ('The Left Hand of Darkness', 'Ursula K. Le Guin', 'to_read', null),
    ('The Dispossessed', 'Ursula K. Le Guin', 'to_read', null),
    ('Hyperion', 'Dan Simmons', 'to_read', null),
    ('Ender''s Game', 'Orson Scott Card', 'to_read', null),
    ('The Three-Body Problem', 'Liu Cixin', 'to_read', null),
    ('Project Hail Mary', 'Andy Weir', 'to_read', null),
    ('The Martian', 'Andy Weir', 'to_read', null),
    ('Klara and the Sun', 'Kazuo Ishiguro', 'to_read', null),
    ('Piranesi', 'Susanna Clarke', 'to_read', null),
    ('Jonathan Strange & Mr Norrell', 'Susanna Clarke', 'to_read', null),
    ('The Fifth Season', 'N. K. Jemisin', 'to_read', null),
    ('American Gods', 'Neil Gaiman', 'to_read', null),
    ('Good Omens', 'Neil Gaiman and Terry Pratchett', 'to_read', null),
    ('Mistborn: The Final Empire', 'Brandon Sanderson', 'to_read', null),
    ('The Way of Kings', 'Brandon Sanderson', 'to_read', null),
    ('A Game of Thrones', 'George R. R. Martin', 'to_read', null),
    ('The Lies of Locke Lamora', 'Scott Lynch', 'to_read', null),
    ('The Blade Itself', 'Joe Abercrombie', 'to_read', null),
    ('Circe', 'Madeline Miller', 'to_read', null),
    ('The Song of Achilles', 'Madeline Miller', 'to_read', null),
    ('Pachinko', 'Min Jin Lee', 'to_read', null),
    ('The Overstory', 'Richard Powers', 'to_read', null),
    ('Lincoln in the Bardo', 'George Saunders', 'to_read', null),
    ('The Underground Railroad', 'Colson Whitehead', 'to_read', null),
    ('The Nickel Boys', 'Colson Whitehead', 'to_read', null),
    ('Normal People', 'Sally Rooney', 'to_read', null),
    ('Conversations with Friends', 'Sally Rooney', 'to_read', null),
    ('The Secret History', 'Donna Tartt', 'to_read', null),
    ('Gone Girl', 'Gillian Flynn', 'to_read', null),
    ('The Girl with the Dragon Tattoo', 'Stieg Larsson', 'to_read', null),
    ('Big Little Lies', 'Liane Moriarty', 'to_read', null),
    ('Where the Crawdads Sing', 'Delia Owens', 'to_read', null),
    ('The Seven Husbands of Evelyn Hugo', 'Taylor Jenkins Reid', 'to_read', null),
    ('Tomorrow, and Tomorrow, and Tomorrow', 'Gabrielle Zevin', 'to_read', null),
    ('Lessons in Chemistry', 'Bonnie Garmus', 'to_read', null),
    ('The Midnight Library', 'Matt Haig', 'to_read', null),
    ('Anxious People', 'Fredrik Backman', 'to_read', null),
    ('A Man Called Ove', 'Fredrik Backman', 'to_read', null),
    ('The Alchemist', 'Paulo Coelho', 'to_read', null),
    ('Siddhartha', 'Hermann Hesse', 'to_read', null),
    ('The Stranger', 'Albert Camus', 'to_read', null),
    ('Meditations', 'Marcus Aurelius', 'to_read', null),
    ('Atomic Habits', 'James Clear', 'to_read', null),
    ('Braiding Sweetgrass', 'Robin Wall Kimmerer', 'to_read', null),
    ('Beowulf', null, 'to_read', null),
    ('The Epic of Gilgamesh', null, 'to_read', null)
  ) as t(title, author, status, rating)
) as v;
